/*
 * Copyright (c) 2017 Nextiva, Inc. to Present.
 * All rights reserved.
 */

package com.nextiva.nextivaapp.android.db.util

object DbConstants {

    const val DATABASE_NAME_CONTACTS = "contacts_database"

    const val TABLE_NAME_CONTACTS = "contacts"
    const val TABLE_NAME_CONTACTS_RECENT = "contacts_recent"
    const val TABLE_NAME_ROOMS = "rooms"
    const val TABLE_NAME_PHONES = "phones"
    const val TABLE_NAME_EMAILS = "emails"
    const val TABLE_NAME_POSTAL_ADDRESSES = "postal_addresses"
    const val TABLE_NAME_VCARDS = "vcards"
    const val TABLE_NAME_MESSAGES = "messages"
    const val TABLE_NAME_PRESENCES = "presences"
    const val TABLE_NAME_CALL_LOG_ENTRIES = "calllogs"
    const val TABLE_NAME_SESSION = "session"
    const val TABLE_NAME_GROUPS = "groups"
    const val TABLE_NAME_GROUP_RELATIONS = "group_relations"
    const val TABLE_NAME_VOICEMAILS = "voicemails"
    const val TABLE_NAME_ATTACHMENTS = "attachments"
    const val TABLE_NAME_THREADS = "threads"
    const val TABLE_NAME_RECIPIENT = "recipient"
    const val TABLE_NAME_SENDER = "sender_table"
    const val TABLE_NAME_SMS_MESSAGE = "sms_messages"
    const val TABLE_NAME_PARTICIPANT = "participant"
    const val TABLE_NAME_MESSAGE_STATE = "message_state"
    const val TABLE_NAME_LOGGING = "logging"
    const val TABLE_NAME_SOCIAL_MEDIA_ACCOUNTS = "social_media_accounts"
    const val TABLE_NAME_DATES = "dates"
    const val TABLE_NAME_SMS_TEAM = "sms_team"
    const val TABLE_NAME_SMS_TEAM_RELATION = "sms_team_relation"
    const val TABLE_NAME_MEETINGS = "meetings"
    const val TABLE_NAME_SCHEDULES = "schedules"
    const val TABLE_NAME_WORKING_HOURS = "working_hours"
    const val TABLE_NAME_WORKING_HOUR_BREAKS = "working_hour_breaks"
    const val TABLE_NAME_HOLIDAYS = "holidays"

    const val CONTACTS_COLUMN_NAME_ID = "id"
    const val CONTACTS_COLUMN_NAME_CONTACT_TYPE_ID = "contact_type_id"
    const val CONTACTS_COLUMN_NAME_CONTACT_TYPE = "contact_type"
    const val CONTACTS_COLUMN_NAME_JID = "jid"
    const val CONTACTS_COLUMN_NAME_DISPLAY_NAME = "display_name"
    const val CONTACTS_COLUMN_NAME_FIRST_NAME = "first_name"
    const val CONTACTS_COLUMN_NAME_LAST_NAME = "last_name"
    const val CONTACTS_COLUMN_NAME_HIRAGANA_FIRST_NAME = "hiragana_first_name"
    const val CONTACTS_COLUMN_NAME_HIRAGANA_LAST_NAME = "hiragana_last_name"
    const val CONTACTS_COLUMN_NAME_TITLE = "title"
    const val CONTACTS_COLUMN_NAME_COMPANY = "company"
    const val CONTACTS_COLUMN_NAME_IS_FAVORITE = "is_favorite"
    const val CONTACTS_COLUMN_NAME_GROUP_ID = "group_id"
    const val CONTACTS_COLUMN_NAME_SHORT_JID = "short_jid"
    const val CONTACTS_COLUMN_NAME_SUBSCRIPTION_STATE = "subscription_state"
    const val CONTACTS_COLUMN_NAME_SORT_NAME = "sort_name"
    const val CONTACTS_COLUMN_NAME_SORT_GROUP = "sort_group"
    const val CONTACTS_COLUMN_NAME_SORT_NAME_FIRST_INITIAL = "sort_name_first_initial"
    const val CONTACTS_COLUMN_NAME_UI_NAME = "ui_name"
    const val CONTACTS_COLUMN_NAME_WEBSITE = "website"
    const val CONTACTS_COLUMN_NAME_DESCRIPTION = "description"
    const val CONTACTS_COLUMN_NAME_DEPARTMENT = "department"
    const val CONTACTS_COLUMN_NAME_CREATED_BY = "created_by"
    const val CONTACTS_COLUMN_NAME_LAST_MODIFIED_BY = "last_modified_by"
    const val CONTACTS_COLUMN_NAME_LAST_MODIFIED_ON = "last_modified_on"
    const val CONTACTS_COLUMN_NAME_TRANSACTION_ID = "transaction_id"
    const val CONTACTS_COLUMN_NAME_LOOKUP_KEY = "lookup_key"
    const val CONTACTS_COLUMN_NAME_ALIASES = "aliases"

    const val VCARDS_COLUMN_NAME_ID = "id"
    const val VCARDS_COLUMN_NAME_CONTACT_ID = "contact_id"
    const val VCARDS_COLUMN_NAME_PHOTO_DATA = "photo_data"
    const val VCARDS_COLUMN_NAME_CALL_ID = "call_id"
    const val VCARDS_COLUMN_NAME_SIP_URI = "sip_uri"
    const val VCARDS_COLUMN_NAME_TRANSACTION_ID = "transaction_id"

    const val PHONES_COLUMN_NAME_ID = "id"
    const val PHONES_COLUMN_NAME_CONTACT_ID = "contact_id"
    const val PHONES_COLUMN_NAME_NUMBER = "number"
    const val PHONES_COLUMN_NAME_STRIPPED_NUMBER = "stripped_number"
    const val PHONES_COLUMN_NAME_TYPE = "type"
    const val PHONES_COLUMN_NAME_LABEL = "label"
    const val PHONES_COLUMN_NAME_EXTENSION = "extension"
    const val PHONES_COLUMN_NAME_PIN_ONE = "pin_one"
    const val PHONES_COLUMN_NAME_PIN_TWO = "pin_two"
    const val PHONES_COLUMN_NAME_TRANSACTION_ID = "transaction_id"

    const val EMAILS_COLUMN_NAME_ID = "id"
    const val EMAILS_COLUMN_NAME_CONTACT_ID = "contact_id"
    const val EMAILS_COLUMN_NAME_ADDRESS = "address"
    const val EMAILS_COLUMN_NAME_TYPE = "type"
    const val EMAILS_COLUMN_NAME_LABEL = "label"
    const val EMAILS_COLUMN_NAME_TRANSACTION_ID = "transaction_id"

    const val POSTAL_ADDRESSES_COLUMN_NAME_ID = "id"
    const val POSTAL_ADDRESSES_COLUMN_NAME_CONTACT_ID = "contact_id"
    const val POSTAL_ADDRESSES_COLUMN_NAME_ADDRESS_LINE_ONE = "address_line_one"
    const val POSTAL_ADDRESSES_COLUMN_NAME_ADDRESS_LINE_TWO = "address_line_two"
    const val POSTAL_ADDRESSES_COLUMN_NAME_POSTAL_CODE = "postal_code"
    const val POSTAL_ADDRESSES_COLUMN_NAME_CITY = "city"
    const val POSTAL_ADDRESSES_COLUMN_NAME_REGION = "region"
    const val POSTAL_ADDRESSES_COLUMN_NAME_COUNTRY = "country"
    const val POSTAL_ADDRESSES_COLUMN_NAME_LOCATION = "location"
    const val POSTAL_ADDRESSES_COLUMN_NAME_TYPE = "type"
    const val POSTAL_ADDRESSES_COLUMN_NAME_TRANSACTION_ID = "transaction_id"

    const val PRESENCES_COLUMN_NAME_ID = "id"
    const val PRESENCES_COLUMN_NAME_CONTACT_ID = "contact_id"
    const val PRESENCES_COLUMN_NAME_USER_ID = "user_id"
    const val PRESENCES_COLUMN_NAME_JID = "jid"
    const val PRESENCES_COLUMN_NAME_PRESENCE_STATE = "presence_state"
    const val PRESENCES_COLUMN_NAME_PRESENCE_TYPE = "presence_type"
    const val PRESENCES_COLUMN_NAME_PRIORITY = "priority"
    const val PRESENCES_COLUMN_NAME_STATUS_TEXT = "status_text"
    const val PRESENCES_COLUMN_NAME_STATUS_EXPIRY_TIME = "status_expiry_time"
    const val PRESENCES_COLUMN_NAME_TRANSACTION_ID = "transaction_id"
    const val PRESENCES_COLUMN_NAME_IN_CALL = "in_call"

    const val MESSAGES_COLUMN_NAME_ID = "id"
    const val MESSAGES_COLUMN_NAME_FROM = "message_from"
    const val MESSAGES_COLUMN_NAME_TO = "message_to"
    const val MESSAGES_COLUMN_NAME_BODY = "body"
    const val MESSAGES_COLUMN_NAME_MESSAGE_ID = "msg_id"
    const val MESSAGES_COLUMN_NAME_TIMESTAMP = "timestamp"
    const val MESSAGES_COLUMN_NAME_IS_READ = "is_read"
    const val MESSAGES_COLUMN_NAME_IS_SENDER = "is_sender"
    const val MESSAGES_COLUMN_NAME_TYPE = "type"
    const val MESSAGES_COLUMN_NAME_GUEST_FIRST = "guest_first"
    const val MESSAGES_COLUMN_NAME_GUEST_LAST = "guest_last"
    const val MESSAGES_COLUMN_NAME_LANGUAGE = "language"
    const val MESSAGES_COLUMN_NAME_PARTICIPANT = "participant"
    const val MESSAGES_COLUMN_NAME_THREAD_ID = "thread_id"
    const val MESSAGES_COLUMN_NAME_CHAT_WITH = "chat_with"
    const val MESSAGES_COLUMN_NAME_MEMBERS = "members"
    const val MESSAGES_COLUMN_NAME_TRANSACTION_ID = "transaction_id"
    const val MESSAGES_COLUMN_NAME_SENT_STATUS = "sent_status"

    const val MESSAGE_STATE_COLUMN_NAME_ID = "message_state_id"
    const val MESSAGE_STATE_COLUMN_NAME_MESSAGE_ID = "message_state_message_id"
    const val MESSAGE_STATE_COLUMN_NAME_PRIORITY = "message_state_priority"
    const val MESSAGE_STATE_COLUMN_NAME_READ_STATUS = "read_status"
    const val MESSAGE_STATE_COLUMN_NAME_DELETED = "deleted"
    const val MESSAGE_STATE_COLUMN_NAME_SMS_ID = "sms_id"

    const val CALL_LOGS_COLUMN_NAME_ID = "id"
    const val CALL_LOGS_COLUMN_NAME_CALL_LOG_ID = "call_log_id"
    const val CALL_LOGS_COLUMN_NAME_DISPLAY_NAME = "display_name"
    const val CALL_LOGS_COLUMN_NAME_CALL_DATE_TIME = "call_date_time"
    const val CALL_LOGS_COLUMN_NAME_COUNTRY_CODE = "country_code"
    const val CALL_LOGS_COLUMN_NAME_PHONE_NUMBER = "phone_number"
    const val CALL_LOGS_COLUMN_NAME_FORMATTED_PHONE_NUMBER = "formatted_phone_number"
    const val CALL_LOGS_COLUMN_NAME_CALL_TYPE = "call_type"
    const val CALL_LOGS_COLUMN_NAME_IS_READ = "is_read"
    const val CALL_LOGS_COLUMN_NAME_CONTACT_ID = "call_with_contact_id"
    const val CALL_LOGS_COLUMN_NAME_PAGE_NUMBER = "call_page_number"
    const val CALL_LOGS_COLUMN_NAME_CALL_DURATION = "call_duration"
    const val CALL_LOGS_COLUMN_NAME_CALL_START_TIME = "call_start_time"

    const val GROUPS_COLUMN_NAME_ID = "id"
    const val GROUPS_COLUMN_NAME_GROUP_ID = "group_id"
    const val GROUPS_COLUMN_NAME_NAME = "name"
    const val GROUPS_COLUMN_NAME_ORDER = "order"
    const val GROUPS_COLUMN_NAME_TRANSACTION_ID = "transaction_id"

    const val GROUPS_RELATION_COLUMN_NAME_CONTACT_ID = "contact_id"
    const val GROUPS_RELATION_COLUMN_NAME_GROUP_ID = "group_id"
    const val GROUPS_RELATION_COLUMN_NAME_TRANSACTION_ID = "transaction_id"

    const val SESSION_COLUMN_NAME_ID = "id"
    const val SESSION_COLUMN_NAME_KEY = "key"
    const val SESSION_COLUMN_NAME_VALUE = "value"

    const val VOICEMAIL_COLUMN_NAME_ID = "id"
    const val VOICEMAIL_COLUMN_NAME_DURATION = "duration"
    const val VOICEMAIL_COLUMN_NAME_ADDRESS = "address"
    const val VOICEMAIL_COLUMN_NAME_NAME = "name"
    const val VOICEMAIL_COLUMN_NAME_CALLER_ID = "caller_id"
    const val VOICEMAIL_COLUMN_NAME_USER_ID = "user_id"
    const val VOICEMAIL_COLUMN_NAME_TIME = "time"
    const val VOICEMAIL_COLUMN_NAME_MESSAGE_ID = "message_id"
    const val VOICEMAIL_COLUMN_NAME_READ = "read"
    const val VOICEMAIL_COLUMN_NAME_TRANSCRIPTION = "transcription"
    const val VOICEMAIL_COLUMN_NAME_FORMATTED_PHONE_NUMBER = "formatted_phone_number"
    const val VOICEMAIL_COLUMN_NAME_RATING = "rating"
    const val VOICEMAIL_COLUMN_NAME_TRANSACTION_ID = "transaction_id"
    const val VOICEMAIL_COLUMN_NAME_ACTUAL_ID = "actual_voicemail_id"
    const val VOICEMAIL_COLUMN_NAME_PAGE_NUMBER = "vm_page_number"

    const val DB_TRUE_STRING_VALUE = "1"
    const val DB_FALSE_STRING_VALUE = "0"

    const val ATTACHMENTS_COLUMN_NAME_ID = "id"
    const val ATTACHMENTS_COLUMN_MESSAGE_ID = "message_id"
    const val ATTACHMENTS_COLUMN_TYPE = "type"
    const val ATTACHMENTS_COLUMN_FILE_NAME = "file_name"
    const val ATTACHMENTS_COLUMN_REFERENCE = "reference"
    const val ATTACHMENTS_COLUMN_LINK = "link"
    const val ATTACHMENTS_COLUMN_CONTENT_TYPE = "content_type"
    const val ATTACHMENTS_COLUMN_SMS_ID = "sms_id"
    const val ATTACHMENTS_COLUMN_CONTENT_DATA = "content_data"
    const val ATTACHMENTS_COLUMN_THUMB_NAIL_LINK = "thumb_nail_link"
    const val ATTACHMENTS_COLUMN_UPLOADED_DATE = "uploaded_date"
    const val ATTACHMENTS_COLUMN_FILE_DURATION = "file_duration"


    const val THREAD_COLUMN_NAME_ID = "id"
    const val THREAD_COLUMN_NAME_MESSAGE_ID = "message_id"
    const val THREAD_COLUMN_NAME_THREAD_ID = "thread_id"

    const val SMS_MESSAGE_COLUMN_NAME_ID = "id"
    const val SMS_MESSAGE_COLUMN_NAME_CHANNEL = "channel"
    const val SMS_MESSAGE_COLUMN_NAME_MESSAGE_ID = "message_id"
    const val SMS_MESSAGE_COLUMN_NAME_BODY = "body"
    const val SMS_MESSAGE_COLUMN_NAME_PREVIEW = "preview"
    const val SMS_MESSAGE_COLUMN_NAME_SENT = "sent"
    const val SMS_MESSAGE_COLUMN_NAME_IS_READ = "is_read"
    const val SMS_MESSAGE_COLUMN_NAME_PRIORITY = "priority"
    const val SMS_MESSAGE_COLUMN_GROUP_VALUE = "group_value"
    const val SMS_MESSAGE_COLUMN_IS_SENDER = "is_sender"
    const val SMS_MESSAGE_COLUMN_MESSAGE_STATE = "message_state"
    const val SMS_MESSAGE_COLUMN_SENT_STATUS = "sent_status"
    const val SMS_MESSAGE_COLUMN_NAME_GROUP_ID = "group_id"
    const val SMS_MESSAGE_COLUMN_NAME_PAGE_NUMBER = "page_number"
    const val SMS_MESSAGE_COLUMN_NAME_CONVERSATION_ID = "conversation_id"

    const val SENDER_COLUMN_NAME_MESSAGE_ID = "message_id"
    const val SENDER_COLUMN_NAME_PARTICIPANT_ID = "participant_id"
    const val SENDER_COLUMN_NAME_PARTICIPANT_PHONE_NUMBER = "participant_phone_number"

    const val RECIPIENT_COLUMN_NAME_MESSAGE_ID = "message_id"
    const val RECIPIENT_COLUMN_NAME_PARTICIPANT_ID = "participant_id"
    const val RECIPIENT_COLUMN_NAME_PARTICIPANT_PHONE_NUMBER = "recipient_phone_number"

    const val PARTICIPANT_COLUMN_NAME_ID = "id"
    const val PARTICIPANT_COLUMN_NAME_NAME = "name"
    const val PARTICIPANT_COLUMN_NAME_EMAIl = "email"
    const val PARTICIPANT_COLUMN_NAME_PHONE_NUMBER = "phone_number"
    const val PARTICIPANT_COLUMN_NAME_TEAM_UUID = "team_uuid"
    const val PARTICIPANT_COLUMN_NAME_USER_UUID = "user_uuid"
    const val PARTICIPANT_COLUMN_NAME_GROUP_ID = "group_id"

    const val SOCIAL_MEDIA_ACCOUNT_COLUMN_NAME_ID = "id"
    const val SOCIAL_MEDIA_ACCOUNT_COLUMN_NAME_CONTACT_ID = "contact_id"
    const val SOCIAL_MEDIA_ACCOUNT_COLUMN_NAME_LINK = "link"
    const val SOCIAL_MEDIA_ACCOUNT_COLUMN_NAME_TYPE = "type"
    const val SOCIAL_MEDIA_ACCOUNT_COLUMN_NAME_TRANSACTION_ID = "transaction_id"

    const val DATE_COLUMN_NAME_ID = "id"
    const val DATE_COLUMN_NAME_CONTACT_ID = "contact_id"
    const val DATE_COLUMN_NAME_DATE = "date"
    const val DATE_COLUMN_NAME_TYPE = "type"
    const val DATE_COLUMN_NAME_TRANSACTION_ID = "transaction_id"

    const val LOGGING_COLUMN_ID = "id"
    const val LOGGING_COLUMN_LEVEL = "level"
    const val LOGGING_COLUMN_MESSAGE = "message"
    const val LOGGING_COLUMN_TIME = "time"
    const val LOGGING_COLUMN_LOCATION = "location"
    const val LOGGING_COLUMN_INTERNET_STATUS = "internet_status"

    const val SMS_TEAM_RELATION_COLUMN_NAME_MESSAGE_ID = "relation_message_id"
    const val SMS_TEAM_RELATION_COLUMN_NAME_TEAM_ID = "relation_team_id"

    const val SMS_TEAM_COLUMN_NAME_ID = "id"
    const val SMS_TEAM_COLUMN_NAME_TEAM_NAME = "team_name"
    const val SMS_TEAM_COLUMN_NAME_TEAM_ID = "team_id"
    const val SMS_TEAM_COLUMN_NAME_TEAM_PHONE_NUMBER = "team_phone_number"
    const val SMS_TEAM_COLUMN_NAME_TEAM_LEGACY_ID = "legacy_Id"

    const val MEETING_COLUMN_NAME_NAME = "name"
    const val MEETING_COLUMN_NAME_START_TIME = "start_time"
    const val MEETING_COLUMN_NAME_CREATED_BY = "created_by"
    const val MEETING_COLUMN_NAME_CALENDAR_ID = "calendar_id"
    const val MEETING_COLUMN_NAME_MEETING_INFO = "meeting_info"

    const val SCHEDULES_COLUMN_NAME_ID = "id"
    const val SCHEDULES_COLUMN_NAME_SCHEDULE_ID = "schedule_id"
    const val SCHEDULES_COLUMN_NAME_IS_24_7 = "is_24_7"
    const val SCHEDULES_COLUMN_NAME_MON_TO_FRI = "mon_to_fri"
    const val SCHEDULES_COLUMN_NAME_NAME = "name"
    const val SCHEDULES_COLUMN_NAME_OLD_SCHEDULE_NAME = "old_schedule_name"
    const val SCHEDULES_COLUMN_NAME_SCHEDULE_LEVEL = "schedule_level"
    const val SCHEDULES_COLUMN_NAME_IS_DND_SCHEDULE = "is_dnd_schedule"
    const val SCHEDULES_COLUMN_NAME_PAGE_NUMBER = "page_number"

    const val WORKING_HOURS_COLUMN_NAME_ID = "id"
    const val WORKING_HOURS_COLUMN_NAME_SCHEDULE_ID = "schedule_id"
    const val WORKING_HOURS_COLUMN_NAME_DAY_ID = "day_id"
    const val WORKING_HOURS_COLUMN_NAME_DAY = "day"
    const val WORKING_HOURS_COLUMN_NAME_END = "end"
    const val WORKING_HOURS_COLUMN_NAME_START = "start"

    const val WORKING_HOUR_BREAKS_COLUMN_NAME_ID = "id"
    const val WORKING_HOUR_BREAKS_COLUMN_NAME_DAY_ID = "day_id"
    const val WORKING_HOUR_BREAKS_COLUMN_NAME_NAME = "name"
    const val WORKING_HOUR_BREAKS_COLUMN_START = "start"
    const val WORKING_HOUR_BREAKS_COLUMN_END = "end"

    const val HOLIDAYS_COLUMN_NAME_ID = "id"
    const val HOLIDAYS_COLUMN_NAME_SCHEDULE_ID = "schedule_id"
    const val HOLIDAYS_COLUMN_NAME_ALL_DAY_EVENT = "all_day_event"
    const val HOLIDAYS_COLUMN_NAME_DAY = "day"
    const val HOLIDAYS_COLUMN_NAME_DAY_OF_WEEK = "day_of_week"
    const val HOLIDAYS_COLUMN_NAME_END_DATE = "end_date"
    const val HOLIDAYS_COLUMN_NAME_TYPE = "type"
    const val HOLIDAYS_COLUMN_NAME_MONTH = "month"
    const val HOLIDAYS_COLUMN_NAME_NAME = "name"
    const val HOLIDAYS_COLUMN_NAME_OCCURRENCE = "occurrence"
    const val HOLIDAYS_COLUMN_NAME_RECURRENCE_RANGE_END_DATE = "recurrence_range_end_date"
    const val HOLIDAYS_COLUMN_NAME_RECURRENCE_RANGE_NUMBER = "recurrence_range_number"
    const val HOLIDAYS_COLUMN_NAME_START_DATE = "start_date"
    const val HOLIDAYS_COLUMN_NAME_START_HOUR = "start_hour"
    const val HOLIDAYS_COLUMN_NAME_END_HOUR = "end_hour"
}
