package com.nextiva.nextivaapp.android.models.net.calendar.events

data class CalendarApiEventDetail(
    val accountId: String? = null,
    val allDay: Boolean? = null,
    val attendees: List<CalendarApiAttendee>? = null,
    val calendarId: Int? = null,
    val corpAccountNumber: String? = null,
    val createdBy: String? = null,
    val description: String? = null,
    val dialInPhone: String? = null,
    val durationInMins: Int? = null,
    val endDate: String? = null,
    var endTime: String,
    val eventId: Int? = null,
    val eventOwner: CalendarApiAttendee? = null,
    val eventType: String? = null,
    val hostEventId: Int? = null,
    val instanceId: Long? = null,
    val linkedAccountEmail: String? = null,
    val location: String? = null,
    val masterEvent: Boolean? = null,
    val masterEventId: String? = null,
    val mediaCallMeetingId: String? = null,
    val meetingPin: String? = null,
    val name: String? = null,
    val nylasEventId: String? = null,
    val recurrence: CalendarApiRecurrence? = null,
    val recurringEvent: Boolean = false,
    val reminderBeforeEventInMins: Int? = null,
    val startDate: String? = null,
    var startTime: String,
    var status: String? = null,
    val tags: String? = null,
    val timeZone: String? = null,
    val userUuid: String? = null,
    val videoConfMeetCode: String? = null,
    val videoConfPassword: String? = null,
    val videoConfPhoneNum: List<String>? = null,
    val videoConfProvider: String? = null,
    val videoConfUrl: String? = null
)