/*
 * Copyright (c) 2022. Nextiva, inc. to Present.
 * All rights reserved
 */

package com.nextiva.nextivaapp.android.meetings.models.net.events

data class MeetingsEventResponse(
    val meetingPin: String? = null,
    val masterEvent: Boolean? = null,
    val endDate: String? = null,
    val description: String? = null,
    val nylasEventId: Any? = null,
    val corpAccountNumber: String? = null,
    val videoConfProvider: Any? = null,
    val mediaCallMeetingId: String? = null,
    val allDay: Boolean? = null,
    val nylasRsvpOnly: Any? = null,
    val myRoomMeetingId: Any? = null,
    val recurringEvent: Boolean? = null,
    val advancedSettings: AdvancedSettings? = null,
    val linkedAccountEmail: String? = null,
    val startTime: Long? = null,
    val videoConfUrl: String? = null,
    val id: String? = null,
    val masterEventId: String? = null,
    val eventId: Int? = null,
    val reminderBeforeEventInMins: Int? = null,
    val attendees: List<AttendeesItem?>? = null,
    val timeZone: String? = null,
    val readOnly: Any? = null,
    val eventType: String? = null,
    val dialIn: Boolean? = null,
    val durationInMins: Int? = null,
    val dialInPhone: String? = null,
    val recurrence: Recurrence? = null,
    val accountId: Any? = null,
    val avoidExternalRequests: Boolean? = null,
    val calendarId: Int? = null,
    val myRoomEnabled: Boolean? = null,
    val createdBy: String? = null,
    val eventOwner: EventOwner? = null,
    val name: String? = null,
    val userUuid: String? = null,
    val videoConfPhoneNum: List<Any?>? = null,
    val location: String? = null,
    val endTime: Long? = null,
    val category: String? = null,
    val startDate: String? = null,
    val hostEventId: Int? = null,
    val videoConfPassword: Any? = null,
    val status: String? = null,
    val videoConfMeetCode: Any? = null,
)